# Generated by Django 4.2 on 2023-07-15 06:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsspu',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='商品详情'),
        ),
    ]
