# Generated by Django 4.2 on 2023-07-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_method',
            field=models.SmallIntegerField(choices=[(3, '支付宝'), (4, '银联支付'), (1, '货到付款'), (2, '微信支付')], default=3, verbose_name='支付方式'),
        ),
    ]
